name: tests

on:
    pull_request:
        types:
            - opened
            - edited
            - synchronize
            - reopened
    push:
        branches:
            - main
            - master
    workflow_dispatch:
        inputs:
            git-ref:
                description: Optional git ref (commit/branch/etc)
                required: false

jobs:

    tests:
        name: tests
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repository (Latest)
              uses: actions/checkout@v3
              if: github.event.inputs.git-ref == ''
            - name: Clone Repository (Custom Ref)
              uses: actions/checkout@v3
              if: github.event.inputs.git-ref != ''
              with:
                ref: ${{ github.event.inputs.git-ref }}
            - name: make zombie and kill
              run: |
                php -d zend.assertions=1 -d assert.exception=1 tests/make_zombie_and_kill.php

